/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ass;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class Postgraduate extends javax.swing.JFrame {

    /**
     * Creates new form Postgraduate
     */
    public Postgraduate() {
        initComponents();
        head_panel.setVisible(true);
        side_panel.setVisible(true);
        add_per_panel.setVisible(false);
        home_panel.setVisible(true);
        update_panel.setVisible(false);
        add_panel.setVisible(false);
        delete_panel.setVisible(false);
        view_panel.setVisible(false);
        view_co_panel.setVisible(false);
        view_per_panel.setVisible(false);
        add_enroll_panel.setVisible(false);
        add_co_panel.setVisible(false);
        add_ass_panel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        center_panel = new javax.swing.JPanel();
        home_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        add_per_panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        index = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        institute = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        contact_no = new javax.swing.JTextField();
        male = new javax.swing.JCheckBox();
        female = new javax.swing.JCheckBox();
        add_insert_b = new javax.swing.JButton();
        qualification = new javax.swing.JComboBox<>();
        add_enroll_panel = new javax.swing.JPanel();
        view_panel = new javax.swing.JPanel();
        view_course = new javax.swing.JButton();
        view_per_de_b = new javax.swing.JButton();
        add_co_panel = new javax.swing.JPanel();
        enroll_subject_b = new javax.swing.JButton();
        add_ass_de_b = new javax.swing.JButton();
        add_ass_panel = new javax.swing.JPanel();
        update_panel = new javax.swing.JPanel();
        view_co_panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        view_per_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        view_index = new javax.swing.JTextField();
        view_per_go = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        per_table = new javax.swing.JTable();
        add_panel = new javax.swing.JPanel();
        add_per_b = new javax.swing.JButton();
        add_co_b = new javax.swing.JButton();
        delete_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        side_panel = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        view = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        head_panel.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Post graduates of NSBM ");

        javax.swing.GroupLayout head_panelLayout = new javax.swing.GroupLayout(head_panel);
        head_panel.setLayout(head_panelLayout);
        head_panelLayout.setHorizontalGroup(
            head_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(head_panelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
        );
        head_panelLayout.setVerticalGroup(
            head_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, head_panelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(head_panel, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout home_panelLayout = new javax.swing.GroupLayout(home_panel);
        home_panel.setLayout(home_panelLayout);
        home_panelLayout.setHorizontalGroup(
            home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_panelLayout.createSequentialGroup()
                .addGap(447, 447, 447)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        home_panelLayout.setVerticalGroup(
            home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_panelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        jLabel6.setText("Index_no");

        jLabel7.setText("Name");

        jLabel8.setText("Gender");

        jLabel9.setText("Qualification");

        jLabel10.setText("Institute");

        jLabel11.setText("NIC");

        jLabel12.setText("Contact_no");

        male.setText("Male");

        female.setText("Female");

        add_insert_b.setText("Insert");
        add_insert_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_insert_bActionPerformed(evt);
            }
        });

        qualification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bsc in computer science", "BE in Information System", "BE in civil engineering", "BE in Electric engineering", "BE in Electronic engineering", "Bcom in Management" }));

        javax.swing.GroupLayout add_per_panelLayout = new javax.swing.GroupLayout(add_per_panel);
        add_per_panel.setLayout(add_per_panelLayout);
        add_per_panelLayout.setHorizontalGroup(
            add_per_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_per_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(add_per_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(add_per_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_per_panelLayout.createSequentialGroup()
                        .addComponent(male)
                        .addGap(18, 18, 18)
                        .addComponent(female))
                    .addComponent(index)
                    .addComponent(name)
                    .addComponent(contact_no)
                    .addComponent(qualification, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(institute)
                    .addComponent(nic))
                .addGap(178, 178, 178))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_per_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_insert_b)
                .addGap(130, 130, 130))
        );
        add_per_panelLayout.setVerticalGroup(
            add_per_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_per_panelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(add_per_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(index, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(19, 19, 19)
                .addGroup(add_per_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(add_per_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(male)
                    .addComponent(female))
                .addGap(18, 18, 18)
                .addGroup(add_per_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(qualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(add_per_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(institute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(add_per_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(add_per_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(contact_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(add_insert_b)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout add_enroll_panelLayout = new javax.swing.GroupLayout(add_enroll_panel);
        add_enroll_panel.setLayout(add_enroll_panelLayout);
        add_enroll_panelLayout.setHorizontalGroup(
            add_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
        add_enroll_panelLayout.setVerticalGroup(
            add_enroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        view_course.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view_course.setText("course details");
        view_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_courseActionPerformed(evt);
            }
        });

        view_per_de_b.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view_per_de_b.setText("personal details");
        view_per_de_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_per_de_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout view_panelLayout = new javax.swing.GroupLayout(view_panel);
        view_panel.setLayout(view_panelLayout);
        view_panelLayout.setHorizontalGroup(
            view_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_panelLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(view_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view_course, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(view_per_de_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        view_panelLayout.setVerticalGroup(
            view_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_panelLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(view_course)
                .addGap(27, 27, 27)
                .addComponent(view_per_de_b)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        enroll_subject_b.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enroll_subject_b.setText("enroll subjects");
        enroll_subject_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enroll_subject_bActionPerformed(evt);
            }
        });

        add_ass_de_b.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_ass_de_b.setText("add_assignment details");
        add_ass_de_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_ass_de_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_co_panelLayout = new javax.swing.GroupLayout(add_co_panel);
        add_co_panel.setLayout(add_co_panelLayout);
        add_co_panelLayout.setHorizontalGroup(
            add_co_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_co_panelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(add_co_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add_ass_de_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enroll_subject_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        add_co_panelLayout.setVerticalGroup(
            add_co_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_co_panelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(enroll_subject_b)
                .addGap(18, 18, 18)
                .addComponent(add_ass_de_b)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout add_ass_panelLayout = new javax.swing.GroupLayout(add_ass_panel);
        add_ass_panel.setLayout(add_ass_panelLayout);
        add_ass_panelLayout.setHorizontalGroup(
            add_ass_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        add_ass_panelLayout.setVerticalGroup(
            add_ass_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout update_panelLayout = new javax.swing.GroupLayout(update_panel);
        update_panel.setLayout(update_panelLayout);
        update_panelLayout.setHorizontalGroup(
            update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );
        update_panelLayout.setVerticalGroup(
            update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );

        jLabel4.setText("Index_no");

        jButton9.setText("GO");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout view_co_panelLayout = new javax.swing.GroupLayout(view_co_panel);
        view_co_panel.setLayout(view_co_panelLayout);
        view_co_panelLayout.setHorizontalGroup(
            view_co_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_co_panelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(view_co_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(view_co_panelLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(44, Short.MAX_VALUE)))
        );
        view_co_panelLayout.setVerticalGroup(
            view_co_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_co_panelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(view_co_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(view_co_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(view_co_panelLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel5.setText("Index_no");

        view_per_go.setText("GO");
        view_per_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_per_goActionPerformed(evt);
            }
        });

        per_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(per_table);

        javax.swing.GroupLayout view_per_panelLayout = new javax.swing.GroupLayout(view_per_panel);
        view_per_panel.setLayout(view_per_panelLayout);
        view_per_panelLayout.setHorizontalGroup(
            view_per_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_per_panelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(view_index, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(view_per_go, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_per_panelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        view_per_panelLayout.setVerticalGroup(
            view_per_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_per_panelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(view_per_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_index, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_per_go)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        add_per_b.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_per_b.setText("Add Personal details");
        add_per_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_per_bActionPerformed(evt);
            }
        });

        add_co_b.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_co_b.setText("add course details");
        add_co_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_co_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_panelLayout = new javax.swing.GroupLayout(add_panel);
        add_panel.setLayout(add_panelLayout);
        add_panelLayout.setHorizontalGroup(
            add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_panelLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add_per_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_co_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        add_panelLayout.setVerticalGroup(
            add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_panelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(add_per_b)
                .addGap(26, 26, 26)
                .addComponent(add_co_b)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jLabel3.setText("Index_no");

        jButton8.setText("GO");

        javax.swing.GroupLayout delete_panelLayout = new javax.swing.GroupLayout(delete_panel);
        delete_panel.setLayout(delete_panelLayout);
        delete_panelLayout.setHorizontalGroup(
            delete_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_panelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        delete_panelLayout.setVerticalGroup(
            delete_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_panelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(delete_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout center_panelLayout = new javax.swing.GroupLayout(center_panel);
        center_panel.setLayout(center_panelLayout);
        center_panelLayout.setHorizontalGroup(
            center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(center_panelLayout.createSequentialGroup()
                .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(delete_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(center_panelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(home_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(center_panelLayout.createSequentialGroup()
                            .addGap(588, 588, 588)
                            .addComponent(add_ass_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(center_panelLayout.createSequentialGroup()
                    .addGap(262, 262, 262)
                    .addComponent(add_per_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE)))
            .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(center_panelLayout.createSequentialGroup()
                    .addGap(262, 262, 262)
                    .addComponent(add_enroll_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(135, Short.MAX_VALUE)))
            .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(center_panelLayout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(view_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(152, Short.MAX_VALUE)))
            .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(center_panelLayout.createSequentialGroup()
                    .addGap(0, 200, Short.MAX_VALUE)
                    .addComponent(add_co_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 199, Short.MAX_VALUE)))
            .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(center_panelLayout.createSequentialGroup()
                    .addGap(307, 307, 307)
                    .addComponent(update_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(339, Short.MAX_VALUE)))
            .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(center_panelLayout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(view_co_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(182, Short.MAX_VALUE)))
            .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(center_panelLayout.createSequentialGroup()
                    .addGap(0, 136, Short.MAX_VALUE)
                    .addComponent(view_per_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 136, Short.MAX_VALUE)))
            .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(center_panelLayout.createSequentialGroup()
                    .addGap(372, 372, 372)
                    .addComponent(add_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        center_panelLayout.setVerticalGroup(
            center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(center_panelLayout.createSequentialGroup()
                .addComponent(home_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add_ass_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
            .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(center_panelLayout.createSequentialGroup()
                    .addGap(199, 199, 199)
                    .addComponent(add_per_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(584, Short.MAX_VALUE)))
            .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(center_panelLayout.createSequentialGroup()
                    .addGap(199, 199, 199)
                    .addComponent(add_enroll_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(625, Short.MAX_VALUE)))
            .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(center_panelLayout.createSequentialGroup()
                    .addGap(281, 281, 281)
                    .addComponent(view_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(518, Short.MAX_VALUE)))
            .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(center_panelLayout.createSequentialGroup()
                    .addGap(0, 440, Short.MAX_VALUE)
                    .addComponent(add_co_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 418, Short.MAX_VALUE)))
            .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(center_panelLayout.createSequentialGroup()
                    .addGap(682, 682, 682)
                    .addComponent(update_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(266, Short.MAX_VALUE)))
            .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(center_panelLayout.createSequentialGroup()
                    .addGap(632, 632, 632)
                    .addComponent(view_co_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(240, Short.MAX_VALUE)))
            .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(center_panelLayout.createSequentialGroup()
                    .addGap(0, 366, Short.MAX_VALUE)
                    .addComponent(view_per_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 344, Short.MAX_VALUE)))
            .addGroup(center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(center_panelLayout.createSequentialGroup()
                    .addGap(375, 375, 375)
                    .addComponent(add_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(426, Short.MAX_VALUE)))
        );

        getContentPane().add(center_panel, java.awt.BorderLayout.CENTER);

        side_panel.setBackground(new java.awt.Color(0, 153, 153));

        add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add.setText("Insert");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        view.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setText("<BACK>");

        javax.swing.GroupLayout side_panelLayout = new javax.swing.GroupLayout(side_panel);
        side_panel.setLayout(side_panelLayout);
        side_panelLayout.setHorizontalGroup(
            side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(side_panelLayout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        side_panelLayout.setVerticalGroup(
            side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_panelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(add)
                .addGap(18, 18, 18)
                .addComponent(update)
                .addGap(18, 18, 18)
                .addComponent(view)
                .addGap(18, 18, 18)
                .addComponent(delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 678, Short.MAX_VALUE)
                .addComponent(back)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        getContentPane().add(side_panel, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
         head_panel.setVisible(true);
        side_panel.setVisible(true);
        add_per_panel.setVisible(false);
        home_panel.setVisible(false);
        update_panel.setVisible(false);
        add_panel.setVisible(false);
        delete_panel.setVisible(false);
        view_panel.setVisible(true);
        view_co_panel.setVisible(false);
        view_per_panel.setVisible(false);
        add_enroll_panel.setVisible(false);
        add_co_panel.setVisible(false);
        add_ass_panel.setVisible(false);
    }//GEN-LAST:event_viewActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
         head_panel.setVisible(true);
        side_panel.setVisible(true);
        add_per_panel.setVisible(false);
        home_panel.setVisible(false);
        update_panel.setVisible(false);
        add_panel.setVisible(true);
        delete_panel.setVisible(false);
        view_panel.setVisible(false);
        view_co_panel.setVisible(false);
        view_per_panel.setVisible(false);
        add_enroll_panel.setVisible(false);
        add_co_panel.setVisible(false);
        add_ass_panel.setVisible(false);
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         head_panel.setVisible(true);
        side_panel.setVisible(true);
        add_per_panel.setVisible(false);
        home_panel.setVisible(false);
        update_panel.setVisible(true);
        add_panel.setVisible(false);
        delete_panel.setVisible(false);
        view_panel.setVisible(false);
        view_co_panel.setVisible(false);
        view_per_panel.setVisible(false);
        add_enroll_panel.setVisible(false);
        add_co_panel.setVisible(false);
        add_ass_panel.setVisible(false);
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         head_panel.setVisible(true);
        side_panel.setVisible(true);
        add_per_panel.setVisible(false);
        home_panel.setVisible(false);
        update_panel.setVisible(false);
        add_panel.setVisible(false);
        delete_panel.setVisible(true);
        view_panel.setVisible(false);
        view_co_panel.setVisible(false);
        view_per_panel.setVisible(false);
        add_enroll_panel.setVisible(false);
        add_co_panel.setVisible(false);
        add_ass_panel.setVisible(false);
    }//GEN-LAST:event_deleteActionPerformed

    private void add_per_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_per_bActionPerformed
        // TODO add your handling code here:
         head_panel.setVisible(true);
        side_panel.setVisible(true);
        add_per_panel.setVisible(true);
        home_panel.setVisible(false);
        update_panel.setVisible(false);
        add_panel.setVisible(false);
        delete_panel.setVisible(false);
        view_panel.setVisible(false);
        view_co_panel.setVisible(false);
        view_per_panel.setVisible(false);
        add_enroll_panel.setVisible(false);
        add_co_panel.setVisible(false);
        add_ass_panel.setVisible(false);
    }//GEN-LAST:event_add_per_bActionPerformed

    private void add_co_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_co_bActionPerformed
        // TODO add your handling code here:
         head_panel.setVisible(true);
        side_panel.setVisible(true);
        add_per_panel.setVisible(false);
        home_panel.setVisible(false);
        update_panel.setVisible(false);
        add_panel.setVisible(false);
        delete_panel.setVisible(false);
        view_panel.setVisible(false);
        view_co_panel.setVisible(false);
        view_per_panel.setVisible(false);
        add_enroll_panel.setVisible(false);
        add_co_panel.setVisible(true);
        add_ass_panel.setVisible(false);
    }//GEN-LAST:event_add_co_bActionPerformed

    private void add_insert_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_insert_bActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/logindb","root","");
            String sql="Insert into per_de_pg VALUES(?,?,?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(sql);
           
            pst.setString(1,index.getText());
            pst.setString(2,name.getText());
            if(male.isSelected()){
                pst.setString(3,"male");}
            else if(female.isSelected()){
                  pst.setString(3,"female");}
             pst.setString(4,qualification.getSelectedItem().toString());
             
           
                pst.setString(5,institute.getText());
                pst.setString(6,contact_no.getText());
                pst.setString(7,nic.getText());
               pst.executeUpdate();
          
                JOptionPane.showMessageDialog(null,"values inserted to database");
                index.setText("");
                 name.setText("");
                 
                 institute.setText("");
                
               contact_no.setText("");
                 nic.setText("");
             
                 
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_add_insert_bActionPerformed

    private void view_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_courseActionPerformed
        // TODO add your handling code here:
          head_panel.setVisible(true);
        side_panel.setVisible(true);
        add_per_panel.setVisible(false);
        home_panel.setVisible(false);
        update_panel.setVisible(false);
        add_panel.setVisible(false);
        delete_panel.setVisible(false);
        view_panel.setVisible(false);
        view_co_panel.setVisible(true);
        view_per_panel.setVisible(false);
        add_enroll_panel.setVisible(false);
        add_co_panel.setVisible(false);
        add_ass_panel.setVisible(false);

        
    }//GEN-LAST:event_view_courseActionPerformed

    private void view_per_de_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_per_de_bActionPerformed
        // TODO add your handling code here:
          head_panel.setVisible(true);
        side_panel.setVisible(true);
        add_per_panel.setVisible(false);
        home_panel.setVisible(false);
        update_panel.setVisible(false);
        add_panel.setVisible(false);
        delete_panel.setVisible(false);
        view_panel.setVisible(false);
        view_co_panel.setVisible(false);
        view_per_panel.setVisible(true);
        add_enroll_panel.setVisible(false);
        add_co_panel.setVisible(false);
        add_ass_panel.setVisible(false);
          DefaultTableModel t_model1=(DefaultTableModel)per_table.getModel();
        t_model1.setRowCount(0);
        
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/logindb","root","");
            String sql="Select * From per_de_pg";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            String colhead[]={"Index_no","Name","Gender","Qualification","Institute","NIC","Contact_no"};
            t_model1.setColumnIdentifiers(colhead);
            ResultSetMetaData rsmd=rs.getMetaData();
            int cols=rsmd.getColumnCount();
            while(rs.next()){
                 Object[] obj=new Object[cols];
                int i;
                for(i=0;i<cols;i++){
                    obj[i]=rs.getObject(i+1);
                    
                }
                t_model1.addRow(obj);
            }
            
            
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
       
            

    }//GEN-LAST:event_view_per_de_bActionPerformed

    private void view_per_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_per_goActionPerformed
        // TODO add your handling code here:
          DefaultTableModel t_model1=(DefaultTableModel)per_table.getModel();
        t_model1.setRowCount(0);
        
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/logindb","root","");
            String sql="Select * From per_de_pg where Index_no='"+view_index.getText()+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            String colhead[]={"Index_no","Name","Gender","Qualification","Institute","NIC","Contact_no"};
            t_model1.setColumnIdentifiers(colhead);
            ResultSetMetaData rsmd=rs.getMetaData();
            int cols=rsmd.getColumnCount();
            while(rs.next()){
                 Object[] obj=new Object[cols];
                int i;
                for(i=0;i<cols;i++){
                    obj[i]=rs.getObject(i+1);
                    
                }
                t_model1.addRow(obj);
            }
            
            
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
       
            
    }//GEN-LAST:event_view_per_goActionPerformed

    private void enroll_subject_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enroll_subject_bActionPerformed
        // TODO add your handling code here:
          head_panel.setVisible(true);
        side_panel.setVisible(true);
        add_per_panel.setVisible(false);
        home_panel.setVisible(false);
        update_panel.setVisible(false);
        add_panel.setVisible(false);
        delete_panel.setVisible(false);
        view_panel.setVisible(false);
        view_co_panel.setVisible(false);
        view_per_panel.setVisible(false);
        add_enroll_panel.setVisible(true);
        add_co_panel.setVisible(false);
        add_ass_panel.setVisible(false);

    }//GEN-LAST:event_enroll_subject_bActionPerformed

    private void add_ass_de_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_ass_de_bActionPerformed
        // TODO add your handling code here:
          head_panel.setVisible(true);
        side_panel.setVisible(true);
        add_per_panel.setVisible(false);
        home_panel.setVisible(false);
        update_panel.setVisible(false);
        add_panel.setVisible(false);
        delete_panel.setVisible(false);
        view_panel.setVisible(false);
        view_co_panel.setVisible(false);
        view_per_panel.setVisible(false);
        add_enroll_panel.setVisible(false);
        add_co_panel.setVisible(false);
        add_ass_panel.setVisible(true);

    }//GEN-LAST:event_add_ass_de_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Postgraduate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Postgraduate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Postgraduate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Postgraduate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Postgraduate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton add_ass_de_b;
    private javax.swing.JPanel add_ass_panel;
    private javax.swing.JButton add_co_b;
    private javax.swing.JPanel add_co_panel;
    private javax.swing.JPanel add_enroll_panel;
    private javax.swing.JButton add_insert_b;
    private javax.swing.JPanel add_panel;
    private javax.swing.JButton add_per_b;
    private javax.swing.JPanel add_per_panel;
    private javax.swing.JButton back;
    private javax.swing.JPanel center_panel;
    private javax.swing.JTextField contact_no;
    private javax.swing.JButton delete;
    private javax.swing.JPanel delete_panel;
    private javax.swing.JButton enroll_subject_b;
    private javax.swing.JCheckBox female;
    private javax.swing.JPanel head_panel;
    private javax.swing.JPanel home_panel;
    private javax.swing.JTextField index;
    private javax.swing.JTextField institute;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JCheckBox male;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nic;
    private javax.swing.JTable per_table;
    private javax.swing.JComboBox<String> qualification;
    private javax.swing.JPanel side_panel;
    private javax.swing.JButton update;
    private javax.swing.JPanel update_panel;
    private javax.swing.JButton view;
    private javax.swing.JPanel view_co_panel;
    private javax.swing.JButton view_course;
    private javax.swing.JTextField view_index;
    private javax.swing.JPanel view_panel;
    private javax.swing.JButton view_per_de_b;
    private javax.swing.JButton view_per_go;
    private javax.swing.JPanel view_per_panel;
    // End of variables declaration//GEN-END:variables
}
